%% Full Lifecycle Investment Assessment for Virtual Power Plant
% 虚拟电厂全生命周期投资评估主程序
%
% This script performs a complete techno-economic lifecycle assessment of
% the VPP described in:
%   "Real-time Operation Strategy of Virtual Power Plants", Applied Energy,
%   2024.
%
% The assessment covers:
%   1. Initial capital expenditure (CAPEX) for all VPP components
%   2. Annual operational revenue from frequency regulation and energy
%      markets, derived from the 14-day simulation results (July 15-28)
%   3. Annual operating expenditure (OPEX): fixed O&M + variable
%      degradation costs
%   4. Battery capacity degradation over project years — modelled with a
%      two-factor (calendar + cycle) empirical model for ES and EV; linear
%      degradation for PV.  Reduced capacity lowers bidding capability and
%      therefore future annual revenue.
%   5. Replacement of the energy-storage battery when its capacity falls
%      below the end-of-life threshold (80%).
%   6. Financial metrics: NPV, IRR, Simple Payback Period, Dynamic
%      (Discounted) Payback Period.
%   7. Sensitivity / scenario analysis across discount rates and
%      degradation rates.
%
% Usage
%   Run this script from the lifecycle_assessment/ directory.
%   Pre-requisites: simulation results must exist in ../results/
%   (result_optimal_bid_ctrl_sep_15.mat … sep_28.mat).
%
% Outputs
%   Printed summary in the Command Window
%   ../results/lifecycle_assessment_result.mat  (saved struct)
%   Plots generated by plot_lifecycle_results.m

clear; clc;

%% -------------------------------------------------------------------------
%  Load Parameters
%  -------------------------------------------------------------------------
lifecycle_parameters;   % loads all CAPEX, degradation, O&M, financial params

%% -------------------------------------------------------------------------
%  Load and Process Daily Simulation Results  (July 15-28, 2020)
%  -------------------------------------------------------------------------
days_available   = 15 : 28;
n_days           = length(days_available);
daily_profits    = zeros(1, n_days);
daily_energy_fees = zeros(1, n_days);
daily_deg_costs  = zeros(1, n_days);

for i = 1 : n_days
    day = days_available(i);
    fname = fullfile('..', 'results', ...
            ['result_optimal_bid_ctrl_sep_' num2str(day) '.mat']);
    load(fname, 'result');
    daily_profits(i)     = sum(result.actualProfit);
    daily_energy_fees(i) = sum(result.actualEnegyFee);
    daily_deg_costs(i)   = sum(result.actualCost);
end

% Representative daily averages (July)
daily_profit_avg         = mean(daily_profits);
daily_energy_fee_avg     = mean(daily_energy_fees);
daily_deg_cost_avg       = mean(daily_deg_costs);
% Gross revenue = market income before operational degradation cost
daily_gross_revenue_avg  = daily_profit_avg + daily_energy_fee_avg;
% Net revenue = gross revenue minus operational degradation cost
daily_revenue_avg        = daily_gross_revenue_avg - daily_deg_cost_avg;

fprintf('=== 每日平均运营指标 (基于7月15-28日模拟结果) ===\n');
fprintf('  每日调频利润:       $%.2f\n', daily_profit_avg);
fprintf('  每日能量收益:       $%.2f\n', daily_energy_fee_avg);
fprintf('  每日运营老化成本:   $%.2f\n', daily_deg_cost_avg);
fprintf('  每日毛收益:         $%.2f\n', daily_gross_revenue_avg);
fprintf('  每日净收益:         $%.2f\n', daily_revenue_avg);
fprintf('\n');

%% -------------------------------------------------------------------------
%  Estimate Daily Energy Throughput for Degradation Model
%  -------------------------------------------------------------------------
% The total actualCost equals:
%   cost = pr_dis_es*(ES discharge MWh) + pr_ch_es*(ES charge MWh)
%        + pr_dis_ev*(EV discharge MWh)
%
% ES and EV cost fractions are estimated from the ES-only simulation runs
% vs. the full-VPP results.  For Day 21 (representative mid-month day):
%   ES cost in full VPP ≈ $972 out of $1 527 total  → ~63.7%
%   EV cost             ≈ remaining 36.3%
% (TCL and IPP have zero degradation cost in this model.)
es_cost_fraction = 0.637;
ev_cost_fraction = 1 - es_cost_fraction;   % 0.363

% Estimated average daily ES energy throughput (one-way, MWh)
% factor of 2: pr_dis_es and pr_ch_es are both $100/MWh (charge + discharge)
daily_es_throughput_mwh  = daily_deg_cost_avg * es_cost_fraction ...
                           / (pr_dis_es + pr_ch_es);

% Estimated average daily EV throughput per vehicle (one-way, kWh)
% EV only pays discharge cost ($150/MWh); charge cost = $0
daily_ev_throughput_kwh  = (daily_deg_cost_avg * ev_cost_fraction ...
                           / pr_dis_ev * 1000) / ev_count;

%% -------------------------------------------------------------------------
%  Annual Revenue and Cost Baseline
%  -------------------------------------------------------------------------
% Scale the representative July daily result to a full year using seasonal
% correction factors defined in lifecycle_parameters.m.
%
% GROSS revenue base: market income (profit + energy fee), before
% subtracting operational degradation cost.  This is the correct top-line
% revenue figure for lifecycle cash-flow analysis; the degradation cost is
% separately modelled as variable OPEX (annual_opex_variable) so that
% both components scale with remaining capacity independently.
annual_gross_revenue_base = daily_gross_revenue_avg * 365 * annual_scaling;
annual_opex_variable      = daily_deg_cost_avg      * 365 * annual_scaling;

fprintf('=== 年度基础收益估算 (折算至全年) ===\n');
fprintf('  年度毛收益 (第1年基准):         $%.2f\n', annual_gross_revenue_base);
fprintf('  年度变动运营成本 (老化, 第1年): $%.2f\n', annual_opex_variable);
fprintf('  年度净收益 (毛收益-变动成本):   $%.2f\n', ...
        annual_gross_revenue_base - annual_opex_variable);
fprintf('  季节性修正系数:                 %.3f\n', annual_scaling);
fprintf('\n');

%% -------------------------------------------------------------------------
%  Capacity Degradation Model
%  -------------------------------------------------------------------------
years = 0 : project_lifetime;   % Year indices 0, 1, …, project_lifetime

deg_params.es_calendar_aging_rate = es_calendar_aging_rate;
deg_params.es_cycle_aging_factor  = es_cycle_aging_factor;
deg_params.es_capacity_mwh        = es_capacity_mwh;
deg_params.es_eol_threshold       = es_eol_threshold;
deg_params.ev_calendar_aging_rate = ev_calendar_aging_rate;
deg_params.ev_cycle_aging_factor  = ev_cycle_aging_factor;
deg_params.ev_capacity_kwh        = ev_capacity_kwh;
deg_params.ev_eol_threshold       = ev_eol_threshold;
deg_params.pv_annual_degradation  = pv_annual_degradation;

[capacity_base, es_cap_base, ev_cap_base, pv_cap] = ...
    capacity_degradation_model(years, daily_es_throughput_mwh, ...
                               daily_ev_throughput_kwh, deg_params);

%% -------------------------------------------------------------------------
%  Determine ES Battery Replacement Years (Multiple Replacements)
%  -------------------------------------------------------------------------
% The ES undergoes repeated replacements whenever its capacity reaches the
% end-of-life threshold (es_eol_threshold = 80%).  Each replacement resets
% the ES capacity to 100%, after which it ages again at the same rate.
% EV and PV are not replaced (EV owners replace their vehicles on their
% own natural cycle, outside the VPP operator's budget).

es_annual_efcs = daily_es_throughput_mwh * 365 / es_capacity_mwh / 2;
ev_annual_efcs = daily_ev_throughput_kwh * 365 / ev_capacity_kwh  / 2;

% Find all ES replacement years using the dedicated helper function.
es_replacement_years = find_es_replacement_years(project_lifetime, es_annual_efcs, ...
    es_calendar_aging_rate, es_cycle_aging_factor, es_eol_threshold);

% Apply each replacement: capacity resets to 100% and ages again.
es_cap = es_cap_base;
for rep_yr = es_replacement_years
    for yr_idx = (rep_yr + 1) : project_lifetime
        k_since = yr_idx - rep_yr;
        n_cyc   = k_since * es_annual_efcs;
        es_cap(yr_idx + 1) = max(1 - k_since * es_calendar_aging_rate ...
                                   - n_cyc   * es_cycle_aging_factor, ...
                                 es_eol_threshold);
    end
end

n_replacements = length(es_replacement_years);
if n_replacements == 0
    fprintf('预计储能系统在 %d 年项目寿命内无需更换\n', project_lifetime);
else
    fprintf('预计储能系统更换 %d 次，年份为: %s (容量将降至 %.0f%%)\n', ...
            n_replacements, num2str(es_replacement_years), ...
            es_eol_threshold * 100);
end
fprintf('\n');

ev_cap = ev_cap_base;

% Weighted capacity combining all resources (weights based on rated power)
w_es    = 0.30;
w_ev    = 0.28;
w_pv    = 0.22;
w_other = 0.20;
capacity = w_es * es_cap + w_ev * ev_cap + w_pv * pv_cap ...
         + w_other * ones(1, length(years));

%% -------------------------------------------------------------------------
%  Annual Cash Flow
%  -------------------------------------------------------------------------
annual_revenue           = zeros(1, project_lifetime);
annual_total_opex        = zeros(1, project_lifetime);
annual_capex_replacement = zeros(1, project_lifetime);

for yr = 1 : project_lifetime
    % Capacity at the start of year yr (index yr+1 in 0-based years array)
    cap = capacity(yr + 1);

    % Revenue scales linearly with available capacity
    % (less capacity → lower bids → lower regulation and energy revenue)
    annual_revenue(yr) = annual_gross_revenue_base * cap ...
                         * (1 + revenue_growth_rate)^(yr - 1);

    % O&M: fixed component + variable degradation (proportional to usage)
    annual_total_opex(yr) = opex_fixed_annual + annual_opex_variable * cap;
end

% ES replacement costs — one cost entry per replacement year
for rep_yr = es_replacement_years
    annual_capex_replacement(rep_yr) = annual_capex_replacement(rep_yr) + capex_es_replace;
end

% Net annual cash flow
annual_cashflow = annual_revenue - annual_total_opex - annual_capex_replacement;

%% -------------------------------------------------------------------------
%  Financial Metrics
%  -------------------------------------------------------------------------

% --- NPV (净现值) ---
npv = -capex_total;
for yr = 1 : project_lifetime
    npv = npv + annual_cashflow(yr) / (1 + discount_rate)^yr;
end

% --- IRR (内部收益率) ---
irr = compute_irr(capex_total, annual_cashflow);

% --- Cumulative cash flows (for payback) ---
cumulative_cashflow     = cumsum(annual_cashflow) - capex_total;
discounted_cashflow     = annual_cashflow ./ (1 + discount_rate) .^ (1:project_lifetime);
cumulative_discounted   = cumsum(discounted_cashflow) - capex_total;

% --- Simple Payback Period (静态回收期) ---
pbp_idx = find(cumulative_cashflow >= 0, 1);
if isempty(pbp_idx)
    simple_pbp = Inf;
elseif pbp_idx == 1
    simple_pbp = capex_total / annual_cashflow(1);
else
    prev = cumulative_cashflow(pbp_idx - 1);
    curr = cumulative_cashflow(pbp_idx);
    simple_pbp = (pbp_idx - 1) + (-prev) / (curr - prev);
end

% --- Dynamic Payback Period (动态回收期 / 折现回收期) ---
dpbp_idx = find(cumulative_discounted >= 0, 1);
if isempty(dpbp_idx)
    dynamic_pbp = Inf;
elseif dpbp_idx == 1
    dynamic_pbp = capex_total / discounted_cashflow(1);
else
    prev = cumulative_discounted(dpbp_idx - 1);
    curr = cumulative_discounted(dpbp_idx);
    dynamic_pbp = (dpbp_idx - 1) + (-prev) / (curr - prev);
end

%% -------------------------------------------------------------------------
%  Print Results Summary  (打印评估结果摘要)
%  -------------------------------------------------------------------------
fprintf('=== 全生命周期投资评估结果摘要 ===\n');
fprintf('项目寿命: %d 年  |  折现率: %.1f%%\n', ...
        project_lifetime, discount_rate * 100);
fprintf('\n');

fprintf('--- 初始投资成本 (CAPEX) ---\n');
fprintf('  光伏系统  (1 MWp PV):         $%d\n',  capex_pv);
fprintf('  储能系统  (2 MWh ES):          $%d\n',  capex_es);
fprintf('  电动汽车基础设施 (40辆 V2G):  $%d\n',  capex_ev_infra);
fprintf('  温控负荷控制 (3栋楼):          $%d\n',  capex_tcl);
fprintf('  工业过程控制 (10流程):         $%d\n',  capex_ipp);
fprintf('  虚拟电厂管理系统:             $%d\n',  capex_vpp_system);
fprintf('  ─────────────────────────────────\n');
fprintf('  总初始投资:                   $%d\n',  capex_total);
fprintf('\n');

fprintf('--- 年度运营指标 (第1年) ---\n');
fprintf('  年度毛收益:         $%.0f\n', annual_revenue(1));
fprintf('  年度固定运维成本:   $%.0f\n', opex_fixed_annual);
fprintf('  年度变动老化成本:   $%.0f\n', annual_opex_variable * capacity(2));
fprintf('  年度净现金流:       $%.0f\n', annual_cashflow(1));
fprintf('\n');

fprintf('--- 容量衰减状况 ---\n');
yr_list = [5, 10, 15, 20];
for k = yr_list
    if k <= project_lifetime
        fprintf('  第%2d年:  综合=%.1f%%  ES=%.1f%%  EV=%.1f%%  PV=%.1f%%\n', ...
                k, capacity(k+1)*100, es_cap(k+1)*100, ...
                ev_cap(k+1)*100, pv_cap(k+1)*100);
    end
end
fprintf('\n');

fprintf('--- 财务指标 ---\n');
fprintf('  净现值 (NPV, %d年, r=%.1f%%): $%.0f\n', ...
        project_lifetime, discount_rate*100, npv);
if ~isnan(irr)
    fprintf('  内部收益率 (IRR):              %.2f%%\n', irr * 100);
else
    fprintf('  内部收益率 (IRR):              无法计算 (项目可能不盈利)\n');
end
if isfinite(simple_pbp)
    fprintf('  简单回收期:                    %.1f 年\n', simple_pbp);
else
    fprintf('  简单回收期:                    超过项目寿命 (%d年)\n', project_lifetime);
end
if isfinite(dynamic_pbp)
    fprintf('  动态回收期 (折现):             %.1f 年\n', dynamic_pbp);
else
    fprintf('  动态回收期 (折现):             超过项目寿命 (%d年)\n', project_lifetime);
end
fprintf('\n');

%% -------------------------------------------------------------------------
%  Scenario Analysis  (情景分析)
%  -------------------------------------------------------------------------
fprintf('=== 情景分析 (折现率 × 衰减倍率) ===\n');
fprintf('%-10s | %-10s | %12s | %8s | %12s\n', ...
        '折现率', '衰减倍率', 'NPV ($)', 'IRR', '动态回收期');
fprintf('%s\n', repmat('-', 1, 60));

for dr = discount_rate_scenarios
    for dm = degradation_scenarios
        % Build scenario degradation params
        dp_s = deg_params;
        dp_s.es_calendar_aging_rate = es_calendar_aging_rate * dm;
        dp_s.es_cycle_aging_factor  = es_cycle_aging_factor  * dm;
        dp_s.ev_calendar_aging_rate = ev_calendar_aging_rate * dm;
        dp_s.ev_cycle_aging_factor  = ev_cycle_aging_factor  * dm;

        [cap_s, ~, ~, ~] = capacity_degradation_model( ...
            years, daily_es_throughput_mwh, daily_ev_throughput_kwh, dp_s);

        % Compute ES replacement years for this scenario using the helper
        es_rep_s = find_es_replacement_years(project_lifetime, es_annual_efcs, ...
            dp_s.es_calendar_aging_rate, dp_s.es_cycle_aging_factor, es_eol_threshold);
        capex_rep_s = zeros(1, project_lifetime);
        for rr = es_rep_s
            capex_rep_s(rr) = capex_rep_s(rr) + capex_es_replace;
        end

        cap_s_yr = cap_s(2:end);   % Years 1 to project_lifetime
        rev_s    = annual_gross_revenue_base * cap_s_yr ...
                   .* (1 + revenue_growth_rate).^(0:project_lifetime-1);
        opex_s   = opex_fixed_annual + annual_opex_variable * cap_s_yr;
        cf_s     = rev_s - opex_s - capex_rep_s;

        npv_s  = -capex_total + sum(cf_s ./ (1+dr).^(1:project_lifetime));
        irr_s  = compute_irr(capex_total, cf_s);

        dcf_s    = cf_s ./ (1+dr).^(1:project_lifetime);
        cum_s    = cumsum(dcf_s) - capex_total;
        didx_s   = find(cum_s >= 0, 1);
        if isempty(didx_s)
            dpbp_s_str = '>寿命';
        elseif didx_s == 1
            dpbp_s_str = sprintf('%.1f年', capex_total / dcf_s(1));
        else
            dpbp_s_str = sprintf('%.1f年', ...
                (didx_s-1) + (-cum_s(didx_s-1))/(cum_s(didx_s)-cum_s(didx_s-1)));
        end

        if ~isnan(irr_s)
            irr_s_str = sprintf('%.1f%%', irr_s * 100);
        else
            irr_s_str = 'N/A';
        end

        fprintf('r=%.0f%%      | %.1fx        | %+12.0f | %8s | %s\n', ...
                dr*100, dm, npv_s, irr_s_str, dpbp_s_str);
    end
end
fprintf('\n');

%% -------------------------------------------------------------------------
%  Save Results  (保存评估结果)
%  -------------------------------------------------------------------------
lifecycle_result.project_lifetime       = project_lifetime;
lifecycle_result.discount_rate          = discount_rate;
lifecycle_result.capex_total            = capex_total;
lifecycle_result.capex_es               = capex_es;
lifecycle_result.capex_pv               = capex_pv;
lifecycle_result.capex_ev_infra         = capex_ev_infra;
lifecycle_result.capex_tcl              = capex_tcl;
lifecycle_result.capex_ipp              = capex_ipp;
lifecycle_result.capex_vpp_system       = capex_vpp_system;
lifecycle_result.years                  = years;
lifecycle_result.es_cap                 = es_cap;
lifecycle_result.ev_cap                 = ev_cap;
lifecycle_result.pv_cap                 = pv_cap;
lifecycle_result.capacity               = capacity;
lifecycle_result.annual_revenue         = annual_revenue;
lifecycle_result.annual_total_opex      = annual_total_opex;
lifecycle_result.annual_capex_replacement = annual_capex_replacement;
lifecycle_result.annual_cashflow        = annual_cashflow;
lifecycle_result.cumulative_cashflow    = cumulative_cashflow;
lifecycle_result.discounted_cashflow    = discounted_cashflow;
lifecycle_result.cumulative_discounted  = cumulative_discounted;
lifecycle_result.npv                    = npv;
lifecycle_result.irr                    = irr;
lifecycle_result.simple_pbp             = simple_pbp;
lifecycle_result.dynamic_pbp            = dynamic_pbp;
lifecycle_result.es_replacement_years    = es_replacement_years;
lifecycle_result.daily_revenue_avg           = daily_revenue_avg;
lifecycle_result.daily_gross_revenue_avg     = daily_gross_revenue_avg;
lifecycle_result.daily_profit_avg            = daily_profit_avg;
lifecycle_result.daily_energy_fee_avg        = daily_energy_fee_avg;
lifecycle_result.daily_deg_cost_avg          = daily_deg_cost_avg;
lifecycle_result.annual_gross_revenue_base   = annual_gross_revenue_base;
lifecycle_result.annual_opex_variable        = annual_opex_variable;
lifecycle_result.opex_fixed_annual           = opex_fixed_annual;

save(fullfile('..', 'results', 'lifecycle_assessment_result.mat'), ...
     'lifecycle_result');
fprintf('评估结果已保存至 ../results/lifecycle_assessment_result.mat\n\n');

%% -------------------------------------------------------------------------
%  Generate Plots  (生成可视化图表)
%  -------------------------------------------------------------------------
plot_lifecycle_results;
